### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by gokul3109**
ported this
https://github.com/OpenPrinting/libppd/commit/0b2ca66bd05966bd1bd4838b9d79be6f83141afc
to the 1.x branch of cups-filters? In cups-filters 1.x the PPD generator is in the file cups-filters/ppd-generator.c.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Thanks for the backport.

I have asked the original reporter of

https://github.com/OpenPrinting/libppd/issues/2

to test it.

**Comment by gokul3109** [comment]
Sure sir, thank you

**Comment by lbschenkel** [comment]
I'm not able to build this PR; I get
```
  CCLD     driverless
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
collect2: error: ld returned 1 exit status
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
make[2]: *** [Makefile:2793: rastertopclx] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2785: rastertoescpx] Error 1
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolutionmake[2]: *** [Makefile:2712: mupdftoraster] Error 1
'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2676: foomatic-rip] Error 1
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2700: imagetoraster] Error 1
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2642: driverless] Error 1
collect2: error: ld returned 1 exit status
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
make[2]: *** [Makefile:2706: implicitclass] Error 1
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2692: imagetopdf] Error 1
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2684: gstoraster] Error 1
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfJoinResolutionArrays'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfNewResolutionArray'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfIPPResToResolution'
/usr/bin/ld: ./.libs/libcupsfilters.so: undefined reference to `cfFreeResolution'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2779: pdftoraster] Error 1
In file included from /usr/include/stdio.h:906,
                 from filter/rastertopdf.cpp:27:
In function ‘int fprintf(FILE*, const char*, ...)’,
    inlined from ‘int main(int, char**)’ at filter/rastertopdf.cpp:1519:16:
/usr/include/bits/stdio2.h:79:24: warning: ‘profile_name’ may be used uninitialized [-Wmaybe-uninitialized]
   79 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   80 |                         __va_arg_pack ());
      |                         ~~~~~~~~~~~~~~~~~
filter/rastertopdf.cpp: In function ‘int main(int, char**)’:
filter/rastertopdf.cpp:1316:25: note: ‘profile_name’ was declared here
 1316 |     const char*         profile_name;   /* IPP Profile Name */
      |                         ^~~~~~~~~~~~
make[2]: Leaving directory '/home/leonardo/Projects/temp/cups-filters/src/cups-filters'
make[1]: *** [Makefile:4856: all-recursive] Error 1
make[1]: Leaving directory '/home/leonardo/Projects/temp/cups-filters/src/cups-filters'
make: *** [Makefile:2089: all] Error 2
```
I can build `1.x` branch of `cups-filters` without any issue; it's only when building this PR that this is happening.

**Comment by tillkamppeter** [comment]
The PR is on the 1.x branch,

So to test it, you clone

https://github.com/gokul3109/cups-filters/tree/1.x

change directory into it, check whether you are in 1.x already, and if not, switch into the 1.x branch. Then you compile.

**Comment by lbschenkel** [comment]
> The PR is on the 1.x branch,
> 
> So to test it, you clone
> 
> https://github.com/gokul3109/cups-filters/tree/1.x
> 
> change directory into it, check whether you are in 1.x already, and if not, switch into the 1.x branch. Then you compile.

I'm aware; this is exactly what I'm doing. The error above is what I get from
https://github.com/gokul3109/cups-filters/tree/1.x
while if I check out and build
https://github.com/OpenPrinting/cups-filters/tree/1.x
it builds without any issue.

**Comment by tillkamppeter** [comment]
@gokul3109 did you try to compile cups-filters 1.x with your changes? Or did you just paste in the code of the original fix in 2.x? Note that the original code uses API functions of 2.x, which do not exist in 1.x, or have another name there. Could you make sure that 1.x builds with your code?

**Comment by lbschenkel** [comment]
Hi again. I suppose that there has been no further progress with this backport?

**Comment by dkosovic** [comment]
I've submitted a new pull request PR# https://github.com/OpenPrinting/cups-filters/pull/532 for cups-filters 1.x that obsoletes this one.

I can confirm that the new pull request is working as I have a printer with the following:
```
print-quality-default (enum) = normal
print-quality-supported (1setOf enum) = normal,high,draft
urf-supported (1setOf keyword) = W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ3-4-5,RS300-600-1200,V1.4,DM1
```

which results in the driverless generated PPD having the following as expected:
```
*OpenUI *cupsPrintQuality/Print Quality: PickOne
*OrderDependency: 10 AnySetup *cupsPrintQuality
*DefaultcupsPrintQuality: Normal
*cupsPrintQuality Draft/Draft: "<</HWResolution[300 300]>>setpagedevice"
*cupsPrintQuality Normal/Normal: "<</HWResolution[600 600]>>setpagedevice"
*cupsPrintQuality High/High: "<</HWResolution[1200 1200]>>setpagedevice"
*CloseUI: *cupsPrintQuality

**Comment by tillkamppeter** [comment]
THanks, @dkosovic Rejecting this one ...

**Pull request closed without merging**
