### PR TITLE
Switched {image→graphics}magick

### LINKED ISSUE #106: Switch from imagemagick to graphicksmagick (or another library)
Imagemagick is problematic since it hijacks a lot of command names (convert, import, …) and has quite a few security problems. There’s more here: http://www.graphicsmagick.org/

### PR DESCRIPTION
**Pull request by flying-sheep**
This looks correct, but I don’t know how to test it properly. Do you have any hints?

Fixes #106

### CODE REVIEW

**Comment by tillkamppeter** [comment]
This patch is completely within the Braille embosser support which is contributed by @sthibaul, so best is if @sthibaul tests this.
@sthibaul, could you please test this patch which convertsthe Braille embosser support from using ImageMagick to GraphicsMagick? Thanks.

**Comment by sthibaul** [comment]
graphicsmagick does not support the .ubrl and .brf formats, so this will just not work at all.

**Comment by tillkamppeter** [comment]
@sthibaul, does this mean that we are forced to use ImageMagick here? Is this the only free software platform which exists that supports these formats?

**Comment by sthibaul** [comment]
AFAIK it's the only software that supports them, yes.

**Comment by tillkamppeter** [comment]
@sthibaul, OK, thanks for the info. I would recommend you to make a feature request to GraphicsMagick to overtake the support for `.ubrl` and `.brf` from ImageMagick.
@flying-sheep, thank you very much for the patch, but as it breaks the functionality of our Braille embosser support, we cannot apply it.

**Comment by flying-sheep** [comment]
of course, makes sense! damn, never heard of those formats, it might indeed be hard to find a replacement.

**Comment by sthibaul** [comment]
I have submitted a patch to graphicsmagick:

https://sourceforge.net/p/graphicsmagick/patches/59/

**Pull request closed without merging**
