### PR TITLE
foomatic-rip: minor code changes

### PR DESCRIPTION
**Pull request by JaiLuthra1**
Used copy_file() function and moved zero-page handling to postscript.c

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Not working at all:
```
till@till-x1yoga:~/printing/openprinting/cups-filters/x$ cat ~/ghostscript/testfiles/CityMap.ps | PPD=../foomatic-pxl.ppd ./foomatic-rip 1 1 1 1 '' > out
DEBUG: Color Manager: Invalid printer name.
'CM Color Calibration' Mode in SPOOLER-LESS: Off
Getting input from file 
foomatic-rip version 1.27.1 running...
Parsing PPD file ...
Added option ColorSpace
Added option Resolution
Added option PageSize
Added option PrintoutMode
Added option ImageableArea
Added option PaperDimension
Added option InputSlot
Added option Duplex
Added option ColorModel
Added option PrinterResolution
Added option Font

Parameter Summary
-----------------

Spooler: cups
Printer: unknown
Shell: /bin/bash
PPD file: ../foomatic-pxl.ppd
ATTR file: 
Printer model: Generic PCL 6/PCL XL Printer Foomatic/pxlcolor (recommended)
Job title: 1
File(s) to be printed:
<STDIN>

Ghostscript extra search path ('GS_LIB'): 
Printing system options:
CM Color Calibration Mode in CUPS: Off
Options from the PPD file:

================================================

File: <STDIN>

================================================

Filetype: PostScript
Storing temporary files in /tmp
No pages left, outputting empty file.

Closing foomatic-rip.
till@till-x1yoga:~/printing/openprinting/cups-filters/x$ 
```

```
till@till-x1yoga:~/printing/openprinting/cups-filters/x$ cat ~/ghostscript/testfiles/launch_leaflet.ps | PPD=../foomatic-pxl.ppd ./foomatic-rip 1 1 1 1 '' > outDEBUG: Color Manager: Invalid printer name.
'CM Color Calibration' Mode in SPOOLER-LESS: Off
Getting input from file 
foomatic-rip version 1.27.1 running...
Parsing PPD file ...
Added option ColorSpace
Added option Resolution
Added option PageSize
Added option PrintoutMode
Added option ImageableArea
Added option PaperDimension
Added option InputSlot
Added option Duplex
Added option ColorModel
Added option PrinterResolution
Added option Font

Parameter Summary
-----------------

Spooler: cups
Printer: unknown
Shell: /bin/bash
PPD file: ../foomatic-pxl.ppd
ATTR file: 
Printer model: Generic PCL 6/PCL XL Printer Foomatic/pxlcolor (recommended)
Job title: 1
File(s) to be printed:
<STDIN>

Ghostscript extra search path ('GS_LIB'): 
Printing system options:
CM Color Calibration Mode in CUPS: Off
Options from the PPD file:

================================================

File: <STDIN>

================================================

Filetype: PostScript
Storing temporary files in /tmp
File contains 6 pages.
Reading PostScript input ...
Job does not start with "%!", is it Postscript?
Process is dying with "Unknown data format.
", exit stat 3
Cleaning up...
till@till-x1yoga:~/printing/openprinting/cups-filters/x$
```

Files used:
[CityMap.ps.txt](https://github.com/OpenPrinting/cups-filters/files/4255990/CityMap.ps.txt)
[launch_leaflet.ps.txt](https://github.com/OpenPrinting/cups-filters/files/4255992/launch_leaflet.ps.txt)
[foomatic-pxl.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4255994/foomatic-pxl.ppd.txt)

**Comment by JaiLuthra1** [comment]
Does it fail only for postscript via stdin or postscript in general?

**Comment by tillkamppeter** [comment]
Only for PostScript via stdin.

**Comment by tillkamppeter** [comment]
@LynxChaus something went wrong with your commenting, you probably wanted to comment in the code. Please go in the web interface of GitHub to the code piece or patch you want to comment on, hover with the mouse over the desired line and click on the blue "+" which pops up. Then you get an input field for a comment.

**Comment by JaiLuthra1** [comment]
@tillkamppeter Comments are displayed properly on the commit

**Comment by tillkamppeter** [comment]
@JaiLuthra1, sorry, appears only in the commit under Code/Commits, not in this Pull Request, probably because the Pull Request was already merged.
@LynxChaus, thanks for the valuable hints.

**Comment by tillkamppeter** [comment]
@JaiLuthra1 @LynxChaus, I think I have got it finally working.
@LynxChaus, I have followed your comments in the code first, getting all in the right order, removing unneeded pieces, make full use of the copy_file() function. After that it still was not working, print_ps() not being able to read the lines (but counting the pages correctly at least). So I had a deeper look and saw that print_ps() tries to couple the temporary file to stdin so that reading stdin reads actually the temporary file. I have removed this detour letting the lines get directly read from the file and it works.
I tested with a 7-page file, a 1-page file, and zero-page files. All show the expected output for me. See my example command lines and files of earlier postings here, these work correctly now.

**Pull request merged**
