### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by LynxChaus**
- reuse existing code for copying file, count pdf pages.
- remove temp file after processing.

Fixes: 37b7d6467dcd ("foomatic-rip: correct handling of jobs")
Signed-off-by: Andrey Jr. Melnikov <temnota.am@gmail.com>

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Thank you very much. I have merged your patch now.

**Comment by tillkamppeter** [comment]
Unfortunately, your patch has broken PostScript input completely and so I have reverted most of it.
Are you aware that foomatic-rip takes both PDF and PostScript as input? Did you test it? Dis you test it with a PostScript input file?

**Comment by LynxChaus** [comment]
I'm printing PDF's with this patch without problem. 

```
/usr/lib/cups/filter/foomatic-rip -v -P HP_LaserJet_1018 /tmp/output.ps 1>/dev/null 
DEBUG: Color Manager: Invalid printer name.
'CM Color Calibration' Mode in SPOOLER-LESS: Off
foomatic-rip version 1.27.1 running...
called with arguments: '-v', '-P', 'HP_LaserJet_1018', '/tmp/output.ps'
Parsing PPD file ...
Added option ColorSpace
Added option PageSize
Added option Quality
Added option Resolution
Added option ImageableArea
Added option PaperDimension
Added option InputSlot
Added option MediaType
Added option Density
Added option Copies
Added option halftone
Added option NupOrient
Added option NupPages
Added option Font

Parameter Summary
-----------------

Spooler: direct
Printer: HP_LaserJet_1018
Shell: /bin/sh
PPD file: /etc/cups/ppd/HP_LaserJet_1018.ppd
ATTR file: 
Printer model: HP LaserJet 1018 Foomatic/foo2zjs-z1 (recommended)
Options: 
Job title: root@ppc
File(s) to be printed:
/tmp/output.ps 

Printing system options:
CM Color Calibration Mode in CUPS: Off
Options from the PPD file:

================================================

File: /tmp/output.ps

================================================

Filetype: PostScript
Reading PostScript input ...
--> This document is DSC-conforming!

-----------
Found: %%BeginProlog
Inserting option code into "Prolog" section.
Found: %%EndProlog

-----------
Found: %%BeginSetup
Inserting option code into "Setup" section.
Found: %%EndSetup

-----------
New page: %%Page: 1 1

Found: %%BeginPageSetup
Inserting option code into "PageSetup" section.
Flushing FIFO.

Starting renderer with command: "foo2zjs-wrapper -z1 -P -L0  -q1    -r1200x600 -p9 -T3 -m1 -s7   -n1 "
Starting process "kid3" (generation 1)
Starting process "kid4" (generation 2)
Starting process "renderer" (generation 2)
JCL: 2345X@PJL
<job data> 


Closing renderer
renderer exited with status 0
kid4 exited with status 0
kid3 finished
kid3 exited with status 0

Closing foomatic-rip.
```

Standard PJL is generated:
```
ESC%-12345X@PJL JOB
@PJL SET JAMRECOVERY=OFF
@PJL SET DENSITY=3
@PJL SET ECONOMODE=OFF
@PJL SET RET=MEDIUM
@PJL INFO STATUS
@PJL USTATUS DEVICE = ON
@PJL USTATUS JOB = ON
@PJL USTATUS PAGE = ON
@PJL USTATUS TIMED = 30
@PJL SET JOBATTR="JobAttr4=20200226115021"^@ESC%-12345XJZJZ
.....
ESC%-12345X@PJL EOJ
ESC%-12345X
```

What is broken?

**Comment by tillkamppeter** [comment]
The problem does not occur when running foomatic-rip with the input file name on the command line, as then your code changes are not exercised. foomatic-rip must get its input fle through stdin.
Try
```
cat /tmp/output.ps | PPD=/etc/cups/ppd/HP_LaserJet_1018.ppd ./foomatic-rip 1 1 1 1 '' > /dev/null
```
This is the way how CUPS executes foomatic-rip in a filter chain or how the wrapper scripts of foo2zjs execute foomatic-rip.

**Comment by LynxChaus** [comment]
Ok, I think - all code inside
```
case PS_FILE:
....
return print_ps(....)
```
is safe to drop. Please, show real empty postrscript file and describe - what you try to achieve with "Zero-page-job" ?

**Comment by tillkamppeter** [comment]
A zero-page job occurs if you for example print a file with 3 pages but with the page-ranges option you select to print page 5-7 of that file. These pages do not exist and so the pdftopdf filter does not leave any page remaining after applying the page-ranges option. The subsequent filters need to handle that correctly, distinguish it from real errors (corrupted or wrong-format files) and ending up without error-exiting, segfaulting, not printing a blank page, and letting CUPS de-queue the job.
See Issue #117 which we have solved on all filters but have still some problems with foomatic-rip.
Note that the situation of a zero-page job can easily happen when mass-printing files with the help of scripts or when simply mis-typing. Users could easily get confused by the job stuck in the queue or even an auto-bug-report pop-up of the Linux distro due to a segfault.

**Comment by LynxChaus** [comment]
Well, broken software generate empty files. But your "workarounds" simply not work:

```
gs -dNODISPLAY -dPARANOIDSAFER -dNOPAUSE -q -c '/pdffile (/tmp/foomatic-0KbQGu.pdf) (r) file runpdfbegin (PageCount: ) print pdfpagecount = quit'
PageCount: 1
```
So, you waste MY CPU time, memory and disk - for nothing. 

[foomatic-0KbQGu.pdf](https://github.com/OpenPrinting/cups-filters/files/4256716/foomatic-0KbQGu.pdf)

Attached [empty.ps.gz](https://github.com/OpenPrinting/cups-filters/files/4258064/empty.ps.gz)
show strange in poscrtipt parser logic:

```
diff --git a/filter/foomatic-rip/postscript.c b/filter/foomatic-rip/postscript.c
index f0ddf018..74404c4c 100644
--- a/filter/foomatic-rip/postscript.c
+++ b/filter/foomatic-rip/postscript.c
@@ -923,11 +923,11 @@ void _print_ps(stream_t *stream)
                                 the beginning of the job or after the last valid
                                 section */
                                 dstrclear(tmp);
-                                if (prologfound)
+                                if (!prologfound)
                                     append_prolog_section(tmp, optset, 1);
-                                if (setupfound)
+                                if (!setupfound)
                                     append_setup_section(tmp, optset, 1);
-                                if (pagesetupfound)
+                                if (!pagesetupfound)
                                     append_page_setup_section(tmp, optset, 1);
                                 dstrinsert(psheader, line_start(psheader->data, insertoptions), tmp->data);
 
@@ -1094,11 +1094,11 @@ void _print_ps(stream_t *stream)
             /* If not done yet, insert defaults and command line settings
             in the beginning of the job or after the last valid section */
             dstrclear(tmp);
-            if (prologfound)
+            if (!prologfound)
                 append_prolog_section(tmp, optset, 1);
-            if (setupfound)
+            if (!setupfound)
                 append_setup_section(tmp, optset, 1);
-            if (pagesetupfound)
+            if (!pagesetupfound)
                 append_page_setup_section(tmp, optset, 1);
             dstrinsert(psheader, line_start(psheader->data, insertoptions), tmp->data);
 
```

**Comment by tillkamppeter** [comment]
With the patch for the parser you are right. I have written the parser many years ago in Perl, and contributor turned it into C later, probably there this bug got introduced. It got never discovered, seems that PostScript files needing this part to work are rare. Also with the time PostScript got fed into foomatic-rip only rarely, as PDF got the standard format for print jobs. I think PostScript gets only fed in when a driver of the foo2zjs package is used, where foomatic-rip is not called by CUPS but out of a wrapper script which comes with the foo2zjs package.
How did you discover this? Which file failed on you leading you to find this bug?
Note that if you find a bug like this that it is best to post a new issue or pull request, as it is a new, independent bug. You do not need any more for this bug though, as I have applied the patch already to my local copy and will commit it soon. Thanks for the report.

Your empty.ps file seems to be originally created by enscript and after that somehow all pages got ripped out. Whatever ripped out the pages did not see that no page was left in the end to then also remove all the unneeded header stuff. How did you obtain this file?

What is wrong with the Ghostscript command line to count the pages in a PDF file? Do you have files where it counts wrong? Or do you have a better, probably more resource-saving method to count the pages in a PDF file? Your file foomatic-0KbQGu.pdf contains 1 empty page, Ghostscript counts correctly here. Do you have a file where you get a wrong page count?

**Comment by LynxChaus** [comment]
> How did you discover this? 

Just see in debug messages. 

>Your empty.ps file seems to be originally created by enscript and after that somehow all pages got ripped out.

No, simply run enscript on empty file: _touch empty.txt && enscript -p empty.ps empty.txt_

>Do you have a file where you get a wrong page count?

No. But I have same question for you - do you have PDF file with zero pages? If it's impossible to get this file in real life - maybe drop PDF pagecounting at all?

**Comment by tillkamppeter** [comment]
The PDF page count was introduced right in the beginning of the PDF support being added, not only when we started to single out zero-page input (Issue #117). It served for going through option settings marked with a page range and so only valid for the selected pages and to split the document into page sets with common options. For this foomatic-rip loops through the pages and needs to know where to stop.
We need to identify zero-page input and distinguish it from really faulty input files as zero-page input should not lead to an error exit code, whereas faulty input should cause an error exit code.
Zero-page PDF files are actually not foreseen by the PDF standard. but filters of older cups-filters versions and perhaps also certain applications can produce them.
An example file is attached, Ghostscript processes it, but with warnings.
The filters of current cups-filters produce zero-byte output when they are supposed to output zero pages of PDF.
[zeropage.pdf](https://github.com/OpenPrinting/cups-filters/files/4261205/zeropage.pdf)

**Comment by LynxChaus** [comment]
just for curiosity - how tell foomatic-rip via CUPS via IPP print selected pages???

> An example file is attached, Ghostscript processes it, but with warnings.

This example simply catch by size, without wake-up shell, big and slow ghostscript, grep..
And may-be better - catch empty output near last filter (PCL/PJL) and abort whole chain of filters.

I still don't understand whole idea of "Zero pages". If here broken filters - it need fixing, if there broken user software - how user know about this? Printing empty page (or page with real error, not like "PS/PCL error #XXYYZZ12BB-44AZ") is better than silently discard print job and do nothing.

PS: time to create tests directory and upload attached here ps/pdf files to it for later testing purposes?

**Pull request merged**
