### PR TITLE
Rewrite bannertopdf to use QPDF instead of Poppler

### LINKED ISSUE #8: bannertopdf should not depend on Poppler
bannertopdf generates PDF files for banner pages and test pages. It does not render existing PDF files, so it does not need a PDF interpreter, so Poppler is not really needed for this task. QPDF would be good enough here. QPDF is a helper to generate and modify PDFs, especially to create a correct XREF table.
Also we want to give the user the liberty to use cups-filters with one single PDF interpreter, one of Ghostscript, Poppler, and MuPDF, so that on devices with low resources (mobile, IoT, ...) one does not need the redundancy of more than one PDF interpreter.
Currently one looses banner and test page functionality if one does not have Poppler installed, so actually only Poppler works as a single PDF interpreter for cups-filters.
It is also possible that bannertopdf uses non-public (internal) APIs of Poppler which can make it easily break with updates of Poppler, but I am not sure whether this is really the case.
Therefore we need to convert bannertopdf to use QPDF instead of Poppler.
Hint: All Poppler use is in filter/pdf.cxx.

### PR DESCRIPTION
**Pull request by sahilarora535**
image

**Introduction**
This pull request caters to the project **["Improving bannertopdf filter to use QPDF instead of Poppler APIs"](https://summerofcode.withgoogle.com/projects/#5640715745361920)** being done as a part of the **[Google Summer of Code Program](https://summerofcode.withgoogle.com/)**, 2018. 

Remove all Poppler code from `bannertopdf` and re-write it using QPDF.

Fixes #8.

Depends on https://github.com/qpdf/qpdf/issues/178 for completion.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
@sahilarora535, QPDF 8.0.2 is released. Does it already contain everything to finish bannertopdf?

**Comment by sahilarora535** [comment]
@tillkamppeter QPDF 8.1.0 has been released, and it contains most of the features required by us. For some of the features like changing font in a form field, I need to see whether we can do it with the current set of features available. I will update you as soon as I am done with the analysis. Until then, I am completing this branch and finalizing it for merging with master branch. I hope that makes sense.

**Comment by tillkamppeter** [comment]
OK, Let us go this way.

**Comment by sahilarora535** [comment]
@tillkamppeter I have pushed more changes to this branch. The status of the work as of now is:
1. The basic functionality of `bannertopdf` is complete. The newly-written filter is able to process forms, fill them with the correct values and produce correct PDFs. It detects whether there is a form or not, and does its work accordingly. It would be very helpful if you could also test it to see if things are according to what we need. The code can be tested using the scripts here: https://github.com/sahilarora535/bannertopdf-test
All you need to do is compile the source on this branch and run the script [`convert`](https://github.com/sahilarora535/bannertopdf-test/blob/master/convert). Basically, I have successfully been able to replace all functionality of Poppler which was being used in `bannertopdf`with QPDF, tested the functionality, and I think this can enable us to get this new filter in Ubuntu 18.10. 
2. The issue raised in #14 has been fixed automatically after replacing Poppler with QPDF.
3. The issue raised in #15 has not been fixed, because essentially in the previous version of `bannertopdf`, header and footer were never even written to the PDF during conversion. I'll have to look into how to write them to the banner file.
4. In the previous version of `bannertopdf` which used Poppler, the `Font-Size` and `Font-Face` were being taken as input, but I could not find `Font-Size` being updated to the PDF, nor was the `Font-Face` being added correctly. I tried changing these attributes but could not see any visible change. The part which deals with changing the font-face looks a bit complicated and it might take some time to understand. There is a lot of font conversions, such as UTF-8 to UTF-16, latin characters, etc., most of which I have very little or almost no idea about. I do not currently know how to do that using QPDF, but am looking into it.
5. I have removed all the conflicts of this branch with master branch so that it can be merged.

Once you test this code and it is upto the mark, I can then refactor it a bit and squash the commits to give it the final touch and then merge it with master. Then we can work on other enhancements as I have mentioned above, since points 3 and 4 above are no breaking changes, just enhancements to `bannertopdf`. Or should I try to fix everything and then push it to master? WDYT on this?

**Comment by tillkamppeter** [comment]
I have tested your QPDF-based `bannertopdf` using your `convert` test script and it works so far. Especially issue #14 is fixed.

What does not work is the logging. All widget names in the log output come out as gibberish, for example:
```
Fill widget name ��tV�U with value N/A.
```
This needs to be fixed, not only to make the logging useful but also to avoid that `bannertopdf` accesses arbitrary memory which it is not supposed to access, as this can cause security problems.
Also log messages of CUPS filters must be CUPS-conforming, usually starting with "DEBUG: ", "DEBUG2:", ...

**Comment by sahilarora535** [comment]
@tillkamppeter I have fixed the issue you mentioned. Thanks a lot for noting them. You can test the changes again. Please let me know if you face any other issues.

**Comment by tillkamppeter** [comment]
Thank you very much. It is working correctly now.

**Comment by tillkamppeter** [comment]
If you fix everything and push it to master would be great, if you have the time and the fixes are not too complicated. Otherwise if it makes the originally intended features working and has no regressions against the Poppler version you could prepare it for merging upstream.

**Comment by jberkenbilt** [comment]
I haven't digested your full message, but I wanted to mention that qpdf 8.1
added some methods for dealing with Unicode strings. They were added
specifically for forms, but they work in other places too. Search for
"UTF-16" in QPDFObjectHandle.hh. The method
QPDFObjectHandle::newUnicodeString takes a UTF-8 encoded std::string as
input and produces a QPDF Object that outputs as a UTF-16-encoded PDF
string. None of the examples use this, but you can look
at qpdf/test_pdf_unicode.cc to see an example of its use. Mostly you don't
have to worry about it, but if you are trying to set form field values to
Unicode strings that are not representable with PDFDocEncoding, this is
what you need.

**Comment by sahilarora535** [comment]
> I haven't digested your full message, but I wanted to mention that qpdf 8.1 added some methods for dealing with Unicode strings. They were added specifically for forms, but they work in other places too. Search for "UTF-16" in QPDFObjectHandle.hh. The method QPDFObjectHandle::newUnicodeString takes a UTF-8 encoded std::string as input and produces a QPDF Object that outputs as a UTF-16-encoded PDF string. None of the examples use this, but you can look at qpdf/test_pdf_unicode.cc to see an example of its use. Mostly you don't have to worry about it, but if you are trying to set form field values to Unicode strings that are not representable with PDFDocEncoding, this is what you need.

@jberkenbilt Thank you very much for your comment on unicode strings and the example file really helped. The previous version of the filter did have a separate routine for converting UTF8 to UTF16.

Also @tillkamppeter the pull request is complete and ready to merge from my side. It would be very helpful if you could review it once and merge it if all is good.

**Pull request merged**
