### PR TITLE
added correct libraries required

### PR DESCRIPTION
**Pull request by mohitmo**
Make fails for me on the current version. This PR includes libraries left for some filters.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
I cannot reproduce your problem. I also think that for your case there is most probably a solution with much less impact. Your patch adds `-lz -lgnutls -lpthread $(AVAHI_LIBS)` to the linker command lines of each executable using libppd. What is especially strange for me is that you are adding `$(AVAHI_LIBS)` to the linker command lines, as libppd does not use Avahi at all. You can grep the whole source code of libppd (`ppd/*.[ch]`) for "avahi" and do not find any occurence.
I have made the output of `make` more verbose, by commenting out the line `AM_SILENT_RULES([yes])` in configure.ac and then grepped the output for `libppd.so` geting all linker command lines for executables and shared objects using libppd:
```
libtool: link: gcc -shared  -fPIC -DPIC  ppd/.libs/libppd_la-ppd-attr.o ppd/.libs/libppd_la-ppd.o ppd/.libs/libppd_la-ppd-cache.o ppd/.libs/libppd_la-ppd-conflicts.o ppd/.libs/libppd_la-ppd-custom.o ppd/.libs/libppd_la-ppd-emit.o ppd/.libs/libppd_la-ppd-localize.o ppd/.libs/libppd_la-ppd-mark.o ppd/.libs/libppd_la-ppd-page.o ppd/.libs/libppd_la-ppd-ipp.o ppd/.libs/libppd_la-array.o ppd/.libs/libppd_la-debug.o ppd/.libs/libppd_la-encode.o ppd/.libs/libppd_la-language.o ppd/.libs/libppd_la-raster-interpret.o ppd/.libs/libppd_la-raster-error.o ppd/.libs/libppd_la-string.o ppd/.libs/libppd_la-snprintf.o ppd/.libs/libppd_la-thread.o   -lcups -lldap -ltiff -ljpeg -ldl  -g -O2   -Wl,-soname -Wl,libppd.so.1 -o .libs/libppd.so.1.0.0
libtool: link: (cd ".libs" && rm -f "libppd.so.1" && ln -s "libppd.so.1.0.0" "libppd.so.1")
libtool: link: (cd ".libs" && rm -f "libppd.so" && ln -s "libppd.so.1.0.0" "libppd.so")
libtool: link: gcc -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/parallel backend/parallel-ieee1284.o backend/parallel-parallel.o  ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/serial backend/serial-serial.o  ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/beh backend/beh-beh.o  ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -shared  -fPIC -DPIC  cupsfilters/.libs/libcupsfilters_la-attr.o cupsfilters/.libs/libcupsfilters_la-check.o cupsfilters/.libs/libcupsfilters_la-cmyk.o cupsfilters/.libs/libcupsfilters_la-colord.o cupsfilters/.libs/libcupsfilters_la-colormanager.o cupsfilters/.libs/libcupsfilters_la-dither.o cupsfilters/.libs/libcupsfilters_la-image.o cupsfilters/.libs/libcupsfilters_la-pdftoippprinter.o cupsfilters/.libs/libcupsfilters_la-image-bmp.o cupsfilters/.libs/libcupsfilters_la-image-colorspace.o cupsfilters/.libs/libcupsfilters_la-image-gif.o cupsfilters/.libs/libcupsfilters_la-image-jpeg.o cupsfilters/.libs/libcupsfilters_la-image-photocd.o cupsfilters/.libs/libcupsfilters_la-image-pix.o cupsfilters/.libs/libcupsfilters_la-image-png.o cupsfilters/.libs/libcupsfilters_la-image-pnm.o cupsfilters/.libs/libcupsfilters_la-image-sgi.o cupsfilters/.libs/libcupsfilters_la-image-sgilib.o cupsfilters/.libs/libcupsfilters_la-image-sun.o cupsfilters/.libs/libcupsfilters_la-image-tiff.o cupsfilters/.libs/libcupsfilters_la-image-zoom.o cupsfilters/.libs/libcupsfilters_la-ipp.o cupsfilters/.libs/libcupsfilters_la-lut.o cupsfilters/.libs/libcupsfilters_la-pack.o cupsfilters/.libs/libcupsfilters_la-ppdgenerator.o cupsfilters/.libs/libcupsfilters_la-raster.o cupsfilters/.libs/libcupsfilters_la-rgb.o cupsfilters/.libs/libcupsfilters_la-srgb.o   -Wl,-rpath -Wl,/home/till/printing/openprinting/cups-filters/x/.libs ./.libs/libppd.so -lcups -lpng16 -lz -lm -ldbus-1 -lldap -ltiff -ljpeg -ldl  -g -O2   -Wl,-soname -Wl,libcupsfilters.so.1 -o .libs/libcupsfilters.so.1.0.0
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/implicitclass backend/implicitclass-implicitclass.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -std=c++0x -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -D_GNU_SOURCE -o .libs/pdftopdf filter/pdftopdf/pdftopdf-pdftopdf.o filter/pdftopdf/pdftopdf-pdftopdf_jcl.o filter/pdftopdf/pdftopdf-pdftopdf_processor.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf_processor.o filter/pdftopdf/pdftopdf-pptypes.o filter/pdftopdf/pdftopdf-nup.o filter/pdftopdf/pdftopdf-intervalset.o filter/pdftopdf/pdftopdf-qpdf_tools.o filter/pdftopdf/pdftopdf-qpdf_xobject.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf.o filter/pdftopdf/pdftopdf-qpdf_cm.o  ./.libs/libppd.so -lqpdf -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/commandtoescpx filter/commandtoescpx-commandtoescpx.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/commandtopclx filter/commandtopclx-commandtopclx.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/sys5ippprinter filter/sys5ippprinter-common.o filter/sys5ippprinter-sys5ippprinter.o  ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/texttotext filter/texttotext-texttotext.o  ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -g -O2 -Wall -D_GNU_SOURCE -o .libs/pdftops filter/pdftops-common.o filter/pdftops-pdftops.o filter/pdf.o  ./.libs/libppd.so -lcups -lqpdf -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -D_PPD_DEPRECATED= -I./cupsfilters/ -I./ppd/ -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/rastertoescpx filter/rastertoescpx-rastertoescpx.o  -lcups ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -D_PPD_DEPRECATED= -I/usr/include/libpng16 -I./cupsfilters/ -I./ppd/ -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/rastertopclx filter/rastertopclx-pcl-common.o filter/rastertopclx-rastertopclx.o  -lcups -lpng16 -lz ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./fontembed/ -I./ppd/ -D_PPD_DEPRECATED= -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/texttopdf filter/texttopdf-common.o filter/texttopdf-pdfutils.o filter/texttopdf-textcommon.o filter/texttopdf-texttopdf.o  ./.libs/libfontembed.so ./.libs/libppd.so -lcups -lfontconfig -lfreetype -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -D_PPD_DEPRECATED= -I./cupsfilters/ -I./ppd/ -g -O2 -Wall -D_GNU_SOURCE -o .libs/rastertopdf filter/rastertopdf-rastertopdf.o  -lcups -llcms2 -lqpdf ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -I./fontembed/ -I./ppd/ -D_PPD_DEPRECATED= -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -Wall -D_GNU_SOURCE -o .libs/bannertopdf filter/bannertopdf-banner.o filter/bannertopdf-bannertopdf.o filter/bannertopdf-pdf.o  ./.libs/libfontembed.so ./.libs/libppd.so -lcups -lpng16 -lz -lqpdf -lfontconfig -lfreetype -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -D_PPD_DEPRECATED= -I./cupsfilters/ -I./ppd/ -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/rastertops filter/rastertops-rastertops.o  -lcups -lz ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -D_GNU_SOURCE -o .libs/pclmtoraster filter/pclmtoraster-pclmtoraster.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lqpdf -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -I/usr/include/libpng16 -I/usr/include/poppler/cpp -I/usr/include/poppler -g -O2 -Wall -D_GNU_SOURCE -o .libs/pdftoraster filter/pdftoraster-pdftoraster.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -llcms2 -lpng16 -lz -lpoppler-cpp -lldap -ltiff -ljpeg -ldl
libtool: link: g++ -g -O2 -Wall -D_GNU_SOURCE -o .libs/gstoraster filter/gstoraster-gstoraster.o filter/pdf.o  -lcups -lqpdf ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -D_PPD_DEPRECATED= -I./cupsfilters/ -I./ppd/ -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/mupdftoraster filter/mupdftoraster-mupdftoraster.o  -lcups ./.libs/libcupsfilters.so ./.libs/libppd.so -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -I/usr/include/libpng16 -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/imagetopdf filter/imagetopdf-common.o filter/imagetopdf-imagetopdf.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lpng16 -lz -lm -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/imagetoraster filter/imagetoraster-common.o filter/imagetoraster-imagetoraster.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lm -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/driverless utils/driverless-driverless.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lldap -ltiff -ljpeg -ldl
libtool: link: gcc -I./cupsfilters/ -I./ppd/ -D_PPD_DEPRECATED= -D_REENTRANT -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE -o .libs/cups-browsed utils/cups_browsed-cups-browsed.o cups_browsed-cups-notifier.o  ./.libs/libcupsfilters.so ./.libs/libppd.so -lcups -lavahi-common -lavahi-client -lavahi-glib -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lldap -ltiff -ljpeg -ldl -pthread
```
They got usually linked for me without libavahi, the few linked with libavahi are using libavahi directly.

So perhaps you have some problem with libtool not building your linker command lines correctly.

Could you run the commands (with your patch NOT applied)
```
make maintainer-clean
./autogen.sh
./configure
make
```
to clean up and rebuild everything? Could you also comment out the line `AM_SILENT_RULES([yes])` in configure.ac and after that run `make` again and attach the output in a file (must have file name extension `.txt`) here?

**Comment by mohitmo** [comment]
> Could you run the commands (with your patch NOT applied)
> 
> ```
> make maintainer-clean
> ./autogen.sh
> ./configure
> make
> ```
> 
> to clean up and rebuild everything? Could you also comment out the line `AM_SILENT_RULES([yes])` in configure.ac and after that run `make` again and attach the output in a file (must have file name extension `.txt`) here?

Please find the make log after commenting out `AM_SILENT_RULES([yes])`
[make_log.txt](https://github.com/OpenPrinting/cups-filters/files/4878503/make_log.txt)

**Comment by tillkamppeter** [comment]
Thanks, I have found the difference between my and your environment now. Your libqpdf is built from source by you (it is in `/usr/loca/...', my libqpdf is a package from my distribution. In you compiler command line libqpdf is specified with an explicit pass to its file but for me `-lqpdf` is specified. The error is also that something is missing for your libqpdf. So most probably something is wrong with your libqpdf build.
Note: If you are using Ubuntu 20.04 (Focal) you can use the distro's libqpdf, it is new enough for current cups-filters.

**Comment by mohitmo** [comment]
> Thanks, I have found the difference between my and your environment now. Your libqpdf is built from source by you (it is in `/usr/loca/...', my libqpdf is a package from my distribution. In you compiler command line libqpdf is specified with an explicit pass to its file but for me `-lqpdf` is specified. The error is also that something is missing for your libqpdf. So most probably something is wrong with your libqpdf build.
> Note: If you are using Ubuntu 20.04 (Focal) you can use the distro's libqpdf, it is new enough for current cups-filters.


I updated to Ubuntu 20.04, but now I am getting an error due to `libcups.a`.

`CXXLD    pdftopdf
/usr/bin/ld: /usr/local/lib/libcups.a(tls.o): undefined reference to symbol 'gnutls_x509_crt_set_activation_time@@GNUTLS_3_4'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: error adding symbols: DSO missing from command line
`

**Comment by tillkamppeter** [comment]
Your libcups is also in `/usr/local/lib/`, meaning that it is your own build. Probably due to your update to Ubuntu 20.04 the libraries used by it got replaced by newer ones. Remove this libcups, 20.04 has its own well-working one.

**Comment by mohitmo** [comment]
> Your libcups is also in `/usr/local/lib/`, meaning that it is your own build. Probably due to your update to Ubuntu 20.04 the libraries used by it got replaced by newer ones. Remove this libcups, 20.04 has its own well-working one.

I removed it but now getting an error due to qpdf

``/usr/bin/ld: filter/pdftopdf/pdftopdf-qpdf_xobject.o: in function `CombineFromContents_Provider::CombineFromContents_Provider(std::vector<QPDFObjectHandle, std::allocator<QPDFObjectHandle> > const&)':
/home/mohitm12/cups-filters/filter/pdftopdf/qpdf_xobject.cc:24: undefined reference to `QPDFObjectHandle::StreamDataProvider::StreamDataProvider(bool)'
/usr/bin/ld: filter/pdftopdf/pdftopdf-qpdf_xobject.o: in function `CombineFromContents_Provider::CombineFromContents_Provider(std::vector<QPDFObjectHandle, std::allocator<QPDFObjectHandle> > const&)':
/home/mohitm12/cups-filters/filter/pdftopdf/qpdf_xobject.cc:24: undefined reference to `QPDFObjectHandle::StreamDataProvider::StreamDataProvider(bool)'
/usr/bin/ld: filter/pdftopdf/pdftopdf-qpdf_xobject.o:(.data.rel.ro._ZTV28CombineFromContents_Provider[_ZTV28CombineFromContents_Provider]+0x28): undefined reference to `QPDFObjectHandle::StreamDataProvider::provideStreamData(int, int, Pipeline*, bool, bool)'
``

I also checked the qpdf version, it is 10.0.1

**Comment by tillkamppeter** [comment]
Could you check the output of your "make" process whether it has references to a libqpdf in `/usr/local/`? Best is not using your own builds of the libraries, but make sure that all libraries of the distro are correctly installed. The distro's libraries and their header files you install automatically with
```
sudo apt build-dep cups-filters
```

**Comment by mohitmo** [comment]
> Could you check the output of your "make" process whether it has references to a libqpdf in `/usr/local/`? Best is not using your own builds of the libraries, but make sure that all libraries of the distro are correctly installed. The distro's libraries and their header files you install automatically with
> 
> ```
> sudo apt build-dep cups-filters
> ```

I checked, it is using  `-lqpdf` and not libqpdf in `/usr/local/`
Please find the log attached.
[make_log.txt](https://github.com/OpenPrinting/cups-filters/files/4883645/make_log.txt)

Also all dependencies are installed for cups-filters, but still this issue is happening.

**Comment by tillkamppeter** [comment]
Your linker command line contains 
```
libtool: link: g++ -std=c++0x -I./ppd/ -I/usr/local/include -g -O2 -Wall -D_GNU_SOURCE -o .libs/pdftopdf filter/pdftopdf/pdftopdf-pdftopdf.o filter/pdftopdf/pdftopdf-pdftopdf_jcl.o filter/pdftopdf/pdftopdf-pdftopdf_processor.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf_processor.o filter/pdftopdf/pdftopdf-pptypes.o filter/pdftopdf/pdftopdf-nup.o filter/pdftopdf/pdftopdf-intervalset.o filter/pdftopdf/pdftopdf-qpdf_tools.o filter/pdftopdf/pdftopdf-qpdf_xobject.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf.o filter/pdftopdf/pdftopdf-qpdf_cm.o  ./.libs/libppd.so -L/usr/local/lib -lqpdf -lcups -ltiff -ljpeg -ldl
```
There is still `-I/usr/local/include` and `-L/usr/local/lib` in the linking command line, pointing the linking process to a, potentially broken, library copy.
Could you run
```
make maintainer-clean
./autogen.sh
./configure
make
```
to get everything cleaned up and re-done.

**Comment by mohitmo** [comment]
> There is still `-I/usr/local/include` and `-L/usr/local/lib` in the linking command line, pointing the linking process to a, potentially broken, library copy.
> Could you run
> 
> ```
> make maintainer-clean
> ./autogen.sh
> ./configure
> make
> ```
> 
> to get everything cleaned up and re-done.

Finally it is resolved.
I checked in `/usr/local` and found that it had qpdf files from my previous local build. Upon deleting them, it worked correctly. Thanks for your help!!
I am closing this PR now.

**Pull request closed without merging**
