### PR TITLE
implicitclass: Set the value of dest_host

### PR DESCRIPTION
**Pull request by deepak0405**
The value of dest_host was not set, because of which `implicitclass` was not handling the `NO_DEST_FOUND` message. Corrected the same in this PR.

Also the cups is setting the value of `cups-browsed-dest-printer` in this case, which should not be sent to the `ipp` backend, so removing that from arguments.

The uri status `HTTP_URI_STATUS_UNKNOWN_SCHEME` is a warning and should be ignored.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Could you clean up your pull request somewhat? Your intended fixes are two changes (first and last commit) in implicitclass.c. The addition of ipp.patch does not make sense at all. Please apply your intended patches to a fresh copy of the original repository. Thanks.

**Comment by tillkamppeter** [comment]
Fixes #152.

**Comment by deepak0405** [comment]
Hey @tillkamppeter, I don't know why git is showing changes in `cups-browsed.c`, I checked the file which is present online, it is not having those changes which the diff is showing.

**Comment by deepak0405** [comment]
@tillkamppeter Corrected the PR.

**Pull request merged**
